=== furby110/Adrian_Ibarra_Practica01/cache.dtd
<!ELEMENT cache (#PCDATA)>
<!ELEMENT directorio (#PCDATA)>
<!ELEMENT archivo (#PCDATA)>
<!ATTLIST directorio nombre CDATA #REQUIRED>
<!ATTLIST directorio tam CDATA #IMPLIED>
<!ATTLIST directorio fecha CDATA #IMPLIED>
<!ATTLIST archivo nombre CDATA #REQUIRED>
<!ATTLIST archivo tam CDATA #REQUIRED>
<!ATTLIST archivo tipo CDATA #REQUIRED>
<!ATTLIST archivo fecha CDATA #REQUIRED>
<!ATTLIST archivo cont CDATA #IMPLIED>

=== furby110/Adrian_Ibarra_Practica01/dist/cache.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE cache SYSTEM "cache.dtd">
<cache>
    <directorio nombre="DirectorioPrivado" tam="1k" fecha="11/02/16"> 
        <archivo nombre="y" tipo=".txt" tam="1k" fecha="hoy">Georgina</archivo>
        <archivo nombre="y" tipo=".algo" tam="1k" fecha="hoy">Britny</archivo>
        <archivo nombre="y" tipo=".algo" tam="1k" fecha="hoy">Viri</archivo>
        <directorio nombre="Women" tam="1k" fecha="11/02/16">
            <archivo nombre="y" tipo=".algo" tam="1k" fecha="hoy">Probando con las locas estas.</archivo>
            <archivo nombre="y" tipo=".algo" tam="1k" fecha="hoy"></archivo>
            <archivo nombre="y" tipo=".algo" tam="1k" fecha="hoy"></archivo>
                <directorio nombre="x" tam="1k" fecha="11/02/16">
                    <archivo nombre="y" tipo=".png" tam="1k" fecha="hoy"></archivo>
                    <archivo nombre="y" tipo=".pdf" tam="1k" fecha="hoy"></archivo>
                </directorio>
        
        </directorio>
    
    </directorio>
    
        <directorio nombre="x" tam="1k" fecha="11/02/16">
            <archivo nombre="y" tipo=".algo" tam="1k" fecha="hoy"></archivo>
            <archivo nombre="y" tipo=".algo" tam="1k" fecha="hoy"></archivo>
            <archivo nombre="y" tipo=".algo" tam="1k" fecha="hoy"></archivo>
        
       
    </directorio>


</cache>
